version: '3.1'


services:

  stats-server:
    build: statistic/service
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123




  stats-db:
    image: postgres:14-alpine
      #ports:
    # - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123


  main-server:
    build: main-service
    depends_on:
      - main-db
      - stats-server
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://main-db:5432/postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      STATS_SERVER_URL: http://stats-server:9090
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8081


  main-db:
    image: postgres:14-alpine
    #ports:
    # - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
