version: '3.1'


services:

  stats-server:
    build: statistic/service
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/postgres




  stats-db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123


  #ewm-service:
   # ports:
    #  - "8080:8080"

  #ewm-db:
   # image: postgres:14-alpine
