server:
  port: 9090

spring:

  mvc:
    format:
      date: "yyyy-MM-dd"
      time: "HH:mm:ss"
      date-time: "yyyy-MM-dd HH:mm:ss"

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


